// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbklPKRTsaXSxwxpuTzmm2EwiIFCyhu2g',
    appId: '1:827979974381:web:c0722be864f2f1d4c9eee4',
    messagingSenderId: '827979974381',
    projectId: 'daftarbelanja-f2d3c',
    authDomain: 'daftarbelanja-f2d3c.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-f2d3c-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-f2d3c.firebasestorage.app',
    measurementId: 'G-WSVTE5FJSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrQlMg_havFQxyQIKByNpUvlaKKcTkMS0',
    appId: '1:827979974381:android:febb79201093ac78c9eee4',
    messagingSenderId: '827979974381',
    projectId: 'daftarbelanja-f2d3c',
    databaseURL: 'https://daftarbelanja-f2d3c-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-f2d3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL8t7sJpZQLu1_mzNZ-Ce9J1RcTrLwZAo',
    appId: '1:827979974381:ios:586caa2d8677c99bc9eee4',
    messagingSenderId: '827979974381',
    projectId: 'daftarbelanja-f2d3c',
    databaseURL: 'https://daftarbelanja-f2d3c-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-f2d3c.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL8t7sJpZQLu1_mzNZ-Ce9J1RcTrLwZAo',
    appId: '1:827979974381:ios:586caa2d8677c99bc9eee4',
    messagingSenderId: '827979974381',
    projectId: 'daftarbelanja-f2d3c',
    databaseURL: 'https://daftarbelanja-f2d3c-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-f2d3c.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbklPKRTsaXSxwxpuTzmm2EwiIFCyhu2g',
    appId: '1:827979974381:web:98ba4dd26e0b55c1c9eee4',
    messagingSenderId: '827979974381',
    projectId: 'daftarbelanja-f2d3c',
    authDomain: 'daftarbelanja-f2d3c.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-f2d3c-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-f2d3c.firebasestorage.app',
    measurementId: 'G-40VFQK4WEB',
  );
}
