// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRNgpOFBoTTso-BOVHOFryS20mzDG4jC4',
    appId: '1:614865934348:web:d551426c5b7ca238023629',
    messagingSenderId: '614865934348',
    projectId: 'mdpgold-e722a',
    authDomain: 'mdpgold-e722a.firebaseapp.com',
    databaseURL: 'https://mdpgold-e722a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mdpgold-e722a.firebasestorage.app',
    measurementId: 'G-EGTQNXVPQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEXGrUpY2BeEYKgO4uUeilNOqUIozGn2I',
    appId: '1:614865934348:android:eed8805c0d40f20d023629',
    messagingSenderId: '614865934348',
    projectId: 'mdpgold-e722a',
    databaseURL: 'https://mdpgold-e722a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mdpgold-e722a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD3-PudmlbxzipTH0deYIp9VvnxKQ3I8g',
    appId: '1:614865934348:ios:b831115cb3d30f38023629',
    messagingSenderId: '614865934348',
    projectId: 'mdpgold-e722a',
    databaseURL: 'https://mdpgold-e722a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mdpgold-e722a.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD3-PudmlbxzipTH0deYIp9VvnxKQ3I8g',
    appId: '1:614865934348:ios:b831115cb3d30f38023629',
    messagingSenderId: '614865934348',
    projectId: 'mdpgold-e722a',
    databaseURL: 'https://mdpgold-e722a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mdpgold-e722a.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRNgpOFBoTTso-BOVHOFryS20mzDG4jC4',
    appId: '1:614865934348:web:ce03b6993f32f01f023629',
    messagingSenderId: '614865934348',
    projectId: 'mdpgold-e722a',
    authDomain: 'mdpgold-e722a.firebaseapp.com',
    databaseURL: 'https://mdpgold-e722a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mdpgold-e722a.firebasestorage.app',
    measurementId: 'G-XK3X73ET0D',
  );
}
